openapi: 3.0.3
info:
  termsOfService: https://termofservice.it
  x-api-id: api-address-manager-private
  x-summary: OpenAPI servizio AddressManager ad uso solo interno
  title: AddressManager
  description: |-
    ## Abstract
    Questo servizio permette di validare, normalizzare e deduplicare indirizzi fisici, nazionali ed internazionali
  contact:
    email: pn@pagopa.it
  license:
    name: PN software license
    url: https://www.pn.pagopa.it/LICENSE
  version: '1.0.0'
servers:
  - url: https://api.addressmanager.pagopa.local
    description: Server url
tags:
  - name: NormalizeAddressService
    description: Operazioni di Normalizzazione Indirizzi
  - name: DedplicatesAddressService
    description: Operazioni di Deduplica e Normalizzazione indirizzi
  - name: HealthCheck
    description: Metodo heartbeat
paths: 
  /:
    get:
      summary: healthCheck 
      description: Servizio di healtCheck
      tags:
        - HealthCheck
      operationId: status
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /address-private/normalize:
    post: 
      summary: Normalizza Indirizzo
      description: Servizio Asincrono per la normalizzazione di un indirizzo. La risposta arriva su una specifica coda da configurare #FIXME: Gestire lista?
      tags:
        - NormalizeAddressService
      operationId: normalize
      parameters: 
        - $ref: "#/components/parameters/AddressCxId"  
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas-pn-address.yaml#/components/schemas/NormalizeRequest"  
        required: true
      responses: 
        "202":
          description: Richiesta di Normalizzazione presa in carico
          content:
            application/json:
              schema:
                $ref: './schemas-pn-address.yaml#/components/schemas/NormalizeAcceptedResponse'
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "500":
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
  /address-private/deduplicates:
    post: 
      summary: Deduplica Indirizzo
      description: Servizio Sincrono per la deduplica di indirizzi. Confronta 2 indirizzi e torna il secondo Normalizzato qualora diverso dal primo 
      tags:
        - DedplicatesAddressService
      operationId: deduplicates
      requestBody:
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              #FIXME: maxItems????
              items:
                $ref: "./schemas-pn-address.yaml#/components/schemas/DeduplicatesRequest"
        required: true
      responses: 
        "200":
          description: Risultato servizio deduplica
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                #FIXME: maxItems????
                items:
                  $ref: './schemas-pn-address.yaml#/components/schemas/DeduplicatesResponse'
        "400":
          description:  Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        "500":
          description: InternalServerError
          content:
            application/problem+json:
              schema:
                $ref: 'remote-refs.yaml#/components/schemas/Problem'
        

  #/address/verify/(cap|nation) 
  #FIXME: Sarebbe utile inserire un servizio sincrono di preverifica CAP Italiano basandoci sulla 
  # lista statica condivisa con il consolidatore, questo permetterebbe di bloccare la creazione della notifica sul nascere
  # qualora si usino cap generici

components: 

  parameters: 
    AddressCxId:
      name: "pn-address-manager-cx-id"
      in: header
      schema:
        type: string
      required: true
  
  securitySchemes:        # ONLY EXTERNAL
    ApiKeyAuth:           # ONLY EXTERNAL
      type: apiKey        # ONLY EXTERNAL
      in: header          # ONLY EXTERNAL
      name: x-api-key     # ONLY EXTERNAL
security:                 # ONLY EXTERNAL
  - ApiKeyAuth: [] # use the same name as under securitySchemes    # ONLY EXTERNAL
              