openapi: 3.0.3
info:
  title:  API fornite dal normalizzatore SINI
  version: 1.0.0
tags:
  - Normalizzatore
paths:
  /send-normalizzatore-ingress/v1/normalizzazione:
    post:
      operationId: normalizzazione
      tags:
        - Normalizzatore
      summary: PN richiede la normalizzazione batch
      description: >-
        Il file in ingresso conterrà i seguenti campi gestiti con logica posizionale (nessuna intestazione, separatore ';'):
          - IdCodiceCliente : Id del cliente
          - Provincia : Sigla Provincia - opzionale
          - Cap : cap - opzionale
          - localita : località/comune - obbligatorio
          - localitaAggiuntiva : frazione - opzionale
          - indirizzo : svia - obbligatorio - contiene la via completa DUG + TOPONIMO + CIVICO
          - indirizzoAggiuntivo : edificio - opzionale
          - stato : sstato - opzionale
        Il processo di normalizzazione creerà un file di output contenente i seguenti campi gestiti con logica posizionale (nessuna intestazione, separatore ';'):
          - IDCODICECLIENTE : Id del cliente;
          - NRISULTATONORM : Risultato di normalizzazione (0 : scartato/ 1,2,3,4,5 : normalizzato);
          - FPOSTALIZZABILE (0 : NON Postalizzabile, 1 : Postalizzabile);
          - NERRORENORM : Codice di errore;
          - SSIGLAPROV : Sigla provincia normalizzata;
          - SSTATOUFF : Stato normalizzato (Valorizzato ITALIA, REPUBBLICA DI SAN MARINO e CITTA' DEL VATICANO + TUTTI GLI STATI ESTERI);
          - SSTATOABB : Stato abbreviato normalizzato;
          - SSTATOSPEDIZIONE : Stato di Spedizione;
          - SCOMUNEUFF : Comune normalizzato;
          - SCOMUNEABB : Comune Abbreviato normalizzato;
          - SCOMUNESPEDIZIONE : Comune di spedizione;
          - SFRAZIONEUFF : Frazione normalizzata;
          - SFRAZIONEABB : Frazione Abbreviata normalizzata;
          - SFRAZIONESPEDIZIONE : Frazione di Spedizione;
          - SCIVICOALTRO : altri elementi del civico (interno, piano, scala, palazzo …) - VA IN INDIRIZZO 2
          - SCAP : cap normalizzato;
          - SPRESSO : informazioni di presso e casella postale (C.P 123, Presso sig. rossi …) -  VA IN NAME 2;
          - SVIACOMPLETAUFF : via completa normalizzata (DUG+COMPL+TOPONIMO+CIVICO POSTALE) ;
          - SVIACOMPLETAABB: via completa normalizzata abbreviata (DUG+COMPL+TOPONIMO+CIVICO POSTALE ABBREVIATA) ;
          - SVIACOMPLETASPEDIZIONE : Indirizzo di Stampa;
        
        NERRORENORM può contenere i seguenti valori
          - 001 : IL CAP NON E' PRESENTE IN INPUT;
          - 002 : LA PROVINCIA NON E' PRESENTE IN INPUT;
          - 003 : IL CAP IN INPUT RISULTA DIVERSO DAL CAP DELLA LOCALITA;
          - 004 : IL CAP IN INPUT RISULTA DIVERSO DAL CAP DELLA VIA;
          - 005 : IL CAP IN INPUT RISULTA DIVERSO DAL CAP DELL'ARCO DI CAP DELLA VIA;
          - 006 : LA SIGLA PROVINCIA IN INPUT RISULTA DIVERSA DA QUELLA DETERMINATA;
          - 007 : IL CAP NON E' PRESENTE NEL RANGE DI CAP CONSENTITI;
          - 008 : LA PROVINCIA NON E' PRESENTE SULLA TABELLA PROVINCIE;
          - 009 : LA PROVINCIA E IL CAP INDIVIDUANO DUE PROVINCIE DIVERSE;
          - 019 : I DATI DI PROVINCE E/O CAP NON SONO VALIDI;
          - 101 : LA LOCALITA' NON E' PRESENTE IN INPUT;
          - 102 : NON E' STATO TROVATO NESSUN CANDIDATO PER LA LOCALITA;
          - 103 : E' STATO TROVATO ALMENO UN CANDIDATO PER QUESTA LOCALITA', MA NESSUNO AVEVA UN PUNTEGGIO TALE DA ESSERE VALIDATO;
          - 104 : SONO STATI TROVATI PIU' CANDIDATI VALIDI PER QUESTA LOCALITA;
          - 105 : LA LOCALITA CANDIDATA NON E' PUBBLICATA;
          - 106 : LA LOCALITA' NON CONGRUENTE CON LO STATO;
          - 107 : LOCALITA' NON TROVATA NELLA PROVINCIA;
          - 108 : LISTA DI LOCALITA' AMBIGUE TRONCATA;
          - 109 : I DATI DELLE LOCALITA' NON SONO VALIDI;
          - 201 : LA FRAZIONE NON E' PRESENTE IN INPUT;
          - 202 : NON E' STATO TROVATO NESSUN CANDIDATO PER LA FRAZIONE;
          - 203 : E' STATO TROVATO ALMENO UN CANDIDATO PER QUESTA FRAZIONE, MA NESSUNO AVEVA UN PUNTEGGIO TALE DA ESSERE VALIDATO;
          - 204 : SONO STATI TROVATI PIU' CANDIDATI VALIDI PER QUESTA FRAZIONE;
          - 301 : LA LOCALITA E LA FRAZIONE INDIVIDUANO DUE COMUNI DIVERSI;
          - 302 : LOCALITA' E FRAZIONE INDICANO FRAZIONI DIVERSE;
          - 303 : LA FRAZIONE NON E' CONGRUENTE CON LA VIA;
          - 401 : LA DUG NON E' PRESENTE IN INPUT;
          - 402 : NON E' STATO TROVATO NESSUN CANDIDATO PER LA DUG;
          - 404 : SONO STATI TROVATI PIU' CANDIDATI VALIDI PER QUESTA DUG;
          - 409 : I DATI DELLE DUG E COMPLEMENTI A DUG NON SONO VALIDI;
          - 421 : LA VIA NON E' PRESENTE IN INPUT;
          - 422 : NON E' STATO TROVATO NESSUN CANDIDATO PER LA VIA;
          - 423 : E' STATO TROVATO ALMENO UN CANDIDATO PER QUESTA VIA, MA NESSUNO AVEVA UN PUNTEGGIO TALE DA ESSERE VALIDATA;
          - 424 : SONO STATI TROVATI PIU' CANDIDATI VALIDI PER QUESTA VIA;
          - 425 : SONO STATE TROVATE IN INPUT ALMENO DUE VIRGOLE;
          - 426 : LA DUG IN INPUT E QUELLA DEL CANDIDATO HANNO DIVERSA MACRODUG;
          - 427 : LA VIA CANDIDATA NON E' PUBBLICATA;
          - 429 : I DATI DELLE VIE NON SONO VALIDI;
          - 430 : LA VIA IN INPUT CORRISPONDE ESATTAMENTE AD UNA FRAZIONE;
          - 441 : SOLO SULLE VIE MULTICAP: NON E' STATO TROVATO IL CIVICO SULL'ARCO DI CAP DELLA VIA;
          - 442 : IL CAP TROVATO SULLA VIA DI UNA LOCALITA' E' INCONGRUENTE CON IL CAP DELLA LOCALITA' TROVATA;
          - 443 : LA VIA NON E' UNIVOCA E ALMENO UNA HA CAP E CIVICO INCONGRUENTI;
          - 449 : I DATI DEGLI ARCHI NON SONO VALIDI;
          - 451 : CASELLA POSTALE CON CAP GENERICO;
          - 452 : LA VIA E' UNA CLAUSOLA DI PRESSO;
          - 459 : INDIRZZO CON CASELLA POSTALE NON VALIDO;
          - 601 : NON E' STATO TROVATO NESSUN CANDIDATO PER LO STATO;
          - 609 : I DATI DEGLI STATI ESTERI NON SONO VALIDI;
          - 901 : ERRORE INTERNO NON CLASSIFICABILE;
          - 997 : ERRORE NEL SERVIZIO DI NORMALIZZAZIONE;
          - 998 : ERRORE FORMATTAZIONE DATI;
          - 999 : CARATTERI NON ASCII PRESENTI NELL'INDIRIZZO;
      parameters:
        - $ref: '#/components/parameters/xPagopaAddrManCxId'
        - $ref: '#/components/parameters/xPagopaAddrManApiKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NormalizzazioneRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalizzazioneResponse'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:


  parameters: 
    xPagopaAddrManCxId:
        name: "pn-address-manager-cx-id"
        in: header
        schema:
          type: string
        required: true
    xPagopaAddrManApiKey:
        name: x-api-key
        description: Credenziale di accesso
        in: header
        required: true
        schema:
          type: string
          x-field-extra-annotation: "@lombok.ToString.Exclude" # NO EXTERNAL


  schemas:
    NormalizzazioneRequest:
      type: object
      required:
        - requestId
        - sha256
        - uri
      properties:
        requestId:
          type: string
          minLength: 1
          maxLength: 250
          description: id lavorazione
        uri:
          type: string
          minLength: 5
          maxLength: 2000
          description: Le coordinate del documento correlato allo stato.
        sha256:
          type: string
          minLength: 40
          maxLength: 50
          description: sha256, codificato in base 64, del contenuto del file riferenziato dal campo uri
        idConf:
          type: string
          description: Eventuale configurazione speciale per la normalizzazione

    NormalizzazioneResponse:
      type: object
      required:
        - requestId
      description: >-
        error valorizzato solo in caso di mancata accettazione
      properties:
        requestId:
          type: string
          minLength: 1
          maxLength: 250
          description: id lavorazione
        error:
          type: string
          description: >-
            identificativo dell'errore            
              - NOR400: BAD REQUEST. Mi passa un input errato sia dal punto di vista del contenuto o formale;
              - NOR401: UNAUTHORIZATED. Mi passa delle credenziali vuote o errate;
              - NOR404: NOT FOUND. Il servizio nel server Postel non è disponibile;
              - NOR500: INTERNAL_SERVER_ERROR. Il servizio nei server Postel non è raggiungibile;
              - NOR998: SERVIZIO DI NORMALIZZAZIONE NON DISPONIBILE; 
    Problem:
      required:
        - type
        - status
        - title
        - errors
      properties:
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 503
          maximum: 600
          minimum: 100
          exclusiveMaximum: true
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: ^[ -~]{0,64}$
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: ^.{0,1024}$
          type: string
        traceId:
          description: Internal support identifier associated to error
          example: 123e4567-e89b-12d3-a456-426614174000
          type: string
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ProblemError'

    ProblemError:
      required:
        - code
      properties:
        code:
          description: Internal code of the error, in human-readable format
          example: PN_PARAMETER_TOO_LONG | PN_PARAMETER_TOO_SHORT | PN_DUPLICATE_ENTRY | etc...
          type: string
        element:
          description: Parameter or request body field name for validation error
          example: 'body.order.item[2].quantity'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 1024
          type: string
