AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  EcsLogGroup:
    Type: String

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 5

  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy.
    Type: Number
    Default: 5

  HealthCheckPath:
    Description: Path endpoint di health check
    Type: String
    Default: '/actuator/health'

  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy.
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String

  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks

  AddressManagerEventBusArn:
    Type: String
    Description: ARN of the address manager event bus

  AddressManagerEventBusName:
    Type: String
    Description: Name of the address manager event bus

  PnCoreTargetEventBus:
    Type: String
    Description: ARN of the core target event bus

  AddressManagerEventBusDLQArn:
    Type: String
    Description: ARN of the address manager event bus DLQ

  AddressManagerEventBusDLQName:
    Type: String
    Description: Name of the address manager event bus DLQ

  AddressManagerEventBusDLQUrl:
    Type: String
    Description: URL of the address manager event bus DLQ

  flagCsv:
    Default: true
    Type: String
    Description: flag to enable csv file check

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'

  CountriesCsv:
    Type: String
    Description: Foreign Countries CSV File

  CapCsv:
    Type: String
    Description: National CAP CSV File

  EnablePatternValidation:
    Type: String
    Default: true
    Description: Boolean to Enable address pattern validationù
    AllowedValues: [true, false]

  PhysicalAddressValidationCharsValue:
    Type: String
    Description: 'Physical address validation. Allowed Characters'
    Default: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ./ '-"

  PnAddressManagerInputsQueueName:
    Type: String
    Description: 'Name for NationalRegistryGatewayInputs'

  PnAddressManagerInputsQueueARN:
    Type: String
    Description: 'ARN for NationalRegistryGatewayInputs'

  PnAddressManagerInputsDLQName:
    Type: String
    Description: 'Queue name for PnAddressManagerInputsDLQ'

  PnAddressManagerInputsDLQARN:
    Type: String
    Description: 'DLQ ARN for PnAddressManagerInputs'

  BatchRequestTableArn:
    Type: String
    Description: 'ARN of DynamoDB table BatchRequest'

  PostelBatchTableArn:
    Type: String
    Description: 'ARN of DynamoDB table PostelBatch'

  CountryTableArn:
    Type: String
    Description: 'ARN of DynamoDB table addressManagerCountry'

  CapTableArn:
    Type: String
    Description: 'ARN of DynamoDB table AddressManagerCap'

  ApiKeyTableArn:
    Type: String
    Description: 'ARN of DynamoDB table AddressManagerApiKey'

  BatchRequestTableName:
    Type: String
    Description: 'NAME of DynamoDB table BatchRequest'

  PostelBatchTableName:
    Type: String
    Description: 'NAME of DynamoDB table PostelBatch'

  CountryTableName:
    Type: String
    Description: 'NAME of DynamoDB table addressManagerCountry'

  CapTableName:
    Type: String
    Description: 'NAME of DynamoDB table AddressManagerCap'

  ApiKeyTableName:
    Type: String
    Description: 'NAME of DynamoDB table AddressManagerApiKey'

  PnAddressManagerNormalizerBatchRequestTtl:
    Type: Number
    Description: 'Postel BatchRequest TTL'
    Default: 1209600

  PnAddressManagerNormalizerBatchRequestDelay:
    Type: Number
    Description: 'Postel batch request delay'
    Default: 30000

  PnAddressManagerNormalizerBatchRequestRecoveryDelay:
    Type: Number
    Description: 'Postel batch request recovery delay'
    Default: 30000

  PnAddressManagerNormalizerPostelRecoveryDelay:
    Type: Number
    Description: 'Postel batch request recovery delay'
    Default: 30000

  PnAddressManagerNormalizerPostelRecoveryAfter:
    Type: Number
    Description: 'Postel Activation recovery after'
    Default: 3600

  PnAddressManagerNormalizerPostelMaxRetry:
    Type: Number
    Description: 'Postel Activation request max retry'
    Default: 3

  PnAddressManagerNormalizerBatchRequestRecoveryAfter:
    Type: Number
    Description: 'Postel batch request recovery after'
    Default: 3600

  PnAddressManagerNormalizerBatchRequestMaxRetry:
    Type: Number
    Description: 'Postel batch request max retry'
    Default: 3

  PnAddressManagerNormalizerBatchRequestMaxSize:
    Type: Number
    Description: 'process postel batch Request max size'
    Default: 100

  PnAddressManagerNormalizerEventBridgeRecoveryDelay:
    Type: Number
    Description: 'EventBridge recovery delay'
    Default: 30000

  PostelCxId:
    Type: String
    Description: 'Postel CxId'

  NormalizerRequestPrefix:
    Type: String
    Description: 'Normalize Request Prefix for Postel requestId'

  PnAddressManagerCxId:
    Type: String
    Description: 'Address manager cxId'

  PnAddressManagerApiKey:
    Type: String
    Description: 'Address manager ApiKey'


Resources:

  # PN-address-manager microservice
  AddressManagerMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-address-manager'
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        HealthCheckPath: !Ref HealthCheckPath
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        AutoscalingStrategy: REST-API
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGION=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_ADDRESSMANAGER_EVENTBUS=${AddressManagerEventBusName}'
        ContainerEnvEntry3: !Sub 'PN_ADDRESSMANAGER_FLAGCSV=${flagCsv}'
        ContainerEnvEntry4: !Sub 'PN_ADDRESSMANAGER_HEALTHCHECKPATH=${HealthCheckPath}'
        ContainerEnvEntry5: !Sub 'PN_ADDRESSMANAGER_COUNTRIESCSV=${CountriesCsv}'
        ContainerEnvEntry6: !Sub 'PN_ADDRESSMANAGER_CAPCSV=${CapCsv}'
        ContainerEnvEntry7: !Sub 'PN_ADDRESSMANAGER_ENABLEPATTERNVALIDATION=${EnablePatternValidation}'
        ContainerEnvEntry8: !Sub 'PN_ADDRESSMANAGER_VALIDATIONPATTERN=${PhysicalAddressValidationCharsValue}'
        ContainerEnvEntry9: !Sub 'PN_ADDRESSMANAGER_TOPICS_GATEWAYEVENTS=${PnAddressManagerInputsQueueName}'
        ContainerEnvEntry10: !Sub 'PN_ADDRESSMANAGER_INPUTQUEUENAME=${PnAddressManagerInputsQueueName}'
        ContainerEnvEntry11: !Sub 'PN_ADDRESSMANAGER_INPUTDLQQUEUENAME=${PnAddressManagerInputsDLQName}'
        ContainerEnvEntry12: !Sub 'PN_ADDRESSMANAGER_POSTELBASEPATH=${PostelBasePath}'
        ContainerEnvEntry13: !Sub 'PN_ADDRESSMANAGER_SAFESTORAGEBASEPATH=${PnSafeStorageBasePath}'
        ContainerEnvEntry14: !Sub 'PN_ADDRESSMANAGER_DAO_APIKEYTABLENAME=${ApiKeyTableName}'
        ContainerEnvEntry15: !Sub 'PN_ADDRESSMANAGER_DAO_CAPTABLENAME=${CapTableName}'
        ContainerEnvEntry16: !Sub 'PN_ADDRESSMANAGER_DAO_COUNTRYTABLENAME=${CountryTableName}'
        ContainerEnvEntry17: !Sub 'PN_ADDRESSMANAGER_DAO_POSTELBATCHTABLENAME=${PostelBatchTableName}'
        ContainerEnvEntry18: !Sub 'PN_ADDRESSMANAGER_DAO_BATCHREQUESTTABLENAME=${BatchRequestTableName}'
        ContainerEnvEntry24: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_TTL=${PnAddressManagerNormalizerBatchRequestTtl}'
        ContainerEnvEntry25: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_DELAY=${PnAddressManagerNormalizerBatchRequestDelay}'
        ContainerEnvEntry26: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_RECOVERYDELAY=${PnAddressManagerNormalizerBatchRequestRecoveryDelay}'
        ContainerEnvEntry27: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_RECOVERYAFTER=${PnAddressManagerNormalizerBatchRequestRecoveryAfter}'
        ContainerEnvEntry28: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_MAXRETRY=${PnAddressManagerNormalizerBatchRequestMaxRetry}'
        ContainerEnvEntry29: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_BATCHREQUEST_MAXSIZE=${PnAddressManagerNormalizerBatchRequestMaxSize}'
        ContainerEnvEntry30: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_EVENTBRIDGE_RECOVERYDELAY=${PnAddressManagerNormalizerEventBridgeRecoveryDelay}'
        ContainerEnvEntry31: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTELCXID=${PostelCxId}'
        ContainerEnvEntry32: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTEL_RECOVERYDELAY=${PnAddressManagerNormalizerPostelRecoveryDelay}'
        ContainerEnvEntry33: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTEL_RECOVERYAFTER=${PnAddressManagerNormalizerPostelRecoveryAfter}'
        ContainerEnvEntry34: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTEL_MAXRETRY=${PnAddressManagerNormalizerPostelMaxRetry}'
        ContainerEnvEntry35: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTEL_REQUESTPREFIX=${NormalizerRequestPrefix}'
        ContainerEnvEntry36: !Sub 'PN_ADDRESSMANAGER_PAGOPACXID=${PnAddressManagerCxId}'
        ContainerSecret1: !Sub 'PN_ADDRESSMANAGER_NORMALIZER_POSTELAUTHKEY=arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:pn-AddressManager-Secrets:PostelApiKey:AWSCURRENT:'
        ContainerSecret2: !Sub 'PN_ADDRESSMANAGER_APIKEY=arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:pn-AddressManager-Secrets:SafeStorageApiKey:AWSCURRENT:'
        MicroServiceSecretPrefix: pn-AddressManager-Secrets

        MappedPaths: '/address-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        TaskRoleManagedPolicyArn: !Ref AddressManagerMicroserviceTaskManagedPolicy
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy

  # CloudWatch dashboard
  AddressManagerMicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-address-manager"
        AlarmArns: !Join
          - ','
          - - !GetAtt AddressManagerMicroservice.Outputs.FatalLogsMetricAlarmArn
            - !GetAtt DLQHasMessagesAlarm.Arn
        LogGroupsNames: !Join
          - ','
          - - !Ref EcsLogGroup
        EventRuleArns: !Join
          - ','
          - - !GetAtt AddressManagerEventBusToTarget.Arn
        QueueArns: !Join
          - ','
          - - !Ref AddressManagerEventBusDLQArn

  AddressManagerMicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - events:PutEvents
            Resource:
              - !Ref AddressManagerEventBusArn
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:GetQueueUrl
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource:
              - !Ref PnAddressManagerInputsDLQARN
              - !Ref PnAddressManagerInputsQueueARN
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Ref CountryTableArn
              - !Ref CapTableArn
              - !Ref ApiKeyTableArn
              - !Ref BatchRequestTableArn
              - !Ref PostelBatchTableArn
              - !Sub '${BatchRequestTableArn}/index/*'
              - !Sub '${PostelBatchTableArn}/index/*'

  ###################
  ### EventBridge ###
  ###################

  # Dead Letter Queue policy
  EventBusDeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AddressManagerEventBusDLQUrl
      PolicyDocument:
        Statement:
          - Sid: "SendEventsToDLQ"
            Effect: "Allow"
            Principal:
              Service:
                - "events.amazonaws.com"
            Action:
              - "SQS:SendMessage"
            Resource:
              - !Ref AddressManagerEventBusDLQArn

  DLQHasMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-AddressManagerBus-DLQ-HasMessage'
      AlarmDescription: "CloudWatch alarm for when DLQ has 1 or more messages."
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value: !Ref AddressManagerEventBusDLQName
      Statistic: "Sum"
      TreatMissingData: "notBreaching"
      Period: 60
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 1
      AlarmActions:
        - !Ref AlarmSNSTopicArn
      InsufficientDataActions:
        - !Ref AlarmSNSTopicArn
      OKActions:
        - !Ref AlarmSNSTopicArn

  # Event Bus to target bus role
  AddressManagerEventBusTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: putEventIntoTargetBus
          PolicyDocument:
            Statement:
              - Sid: putEvents
                Action:
                  - events:PutEvents
                Effect: Allow
                Resource:
                  - !Ref PnCoreTargetEventBus

  # Event Bus rule that direct event to target event bus
  AddressManagerEventBusToTarget:
    Type: AWS::Events::Rule
    Properties:
      Description: Route Address Manager Events to target event bus
      RoleArn: !GetAtt AddressManagerEventBusTargetRole.Arn
      EventBusName: !Ref AddressManagerEventBusName
      EventPattern:
        detail-type: [ "AddressManagerOutcomeEvent" ]
        source: [ "pn-address-manager" ]
      Targets:
        - Id: !Sub '${ProjectName}-AddressManagerBus-PnCoreTargetEventBus'
          Arn: !Ref PnCoreTargetEventBus
          RoleArn: !GetAtt AddressManagerEventBusTargetRole.Arn
          DeadLetterConfig:
            Arn: !Ref AddressManagerEventBusDLQArn
