AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogRetention:
    Type: Number
    Default: 14

Resources:
  # Log group
  PnAddressManagerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-address-manager"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/ecs'

  # Event Bus
  AddressManagerEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${ProjectName}-AddressManagerBus'

  # Event Bus Dead Letter Queue
  AddressManagerEventBusDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${ProjectName}-AddressManagerBus-DLQ'

  ApiKeyTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-address-manager-apiKey'
      AttributeDefinitions:
        - AttributeName: "apiKeyId"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "apiKeyId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CapTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-address-manager-cap'
      AttributeDefinitions:
        - AttributeName: "cap"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cap"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Batch Request Table
  BatchRequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-batchRequests'
      AttributeDefinitions:
        - AttributeName: "correlationId"
          AttributeType: "S"
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastReserved"
          AttributeType: "S"
        - AttributeName: "sendStatus"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correlationId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "batchId-lastReserved-index"
          KeySchema:
            - AttributeName: batchId
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: "sendStatus-lastReserved-index"
          KeySchema:
            - AttributeName: sendStatus
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: true

  # Batch Postel Table
  BatchPostelTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-postel-batch'
      AttributeDefinitions:
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastReserved"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "batchId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-lastReserved-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"

Outputs:
  EcsLogGroup:
    Value: !GetAtt PnAddressManagerLogGroup.Outputs.LogGroupName
  AddressManagerEventBusArn:
    Value: !GetAtt AddressManagerEventBus.Arn
  AddressManagerEventBusName:
    Value: !GetAtt AddressManagerEventBus.Name
  AddressManagerEventBusDLQArn:
    Value: !GetAtt AddressManagerEventBusDLQ.Arn
  AddressManagerEventBusDLQName:
    Value: !GetAtt AddressManagerEventBusDLQ.QueueName
  AddressManagerEventBusDLQUrl:
    Value: !GetAtt AddressManagerEventBusDLQ.QueueUrl
