AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogRetention:
    Type: Number
    Default: 14
  
  AlarmSNSTopicName:
    Type: String


Resources:
  # Log group
  PnAddressManagerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-address-manager"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/ecs'

  # Event Bus
  AddressManagerEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${ProjectName}-AddressManagerBus'

  # Event Bus Dead Letter Queue
  AddressManagerEventBusDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${ProjectName}-AddressManagerBus-DLQ'

  # Coda per interna per memorizzare richieste al gateway
  # NB: usati i valori di default per: DelaySeconds, DeadLetterQueueName, MessageRetentionPeriod, MaxReceiveCount, DeadLetterMessageRetentionPeriod,
  PnAddressManagerInputsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-address_manager_inputs'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1

  # Coda per interna per memorizzare chiamate alla callback da parte di Postel
  # NB: usati i valori di default per: DelaySeconds, DeadLetterQueueName, MessageRetentionPeriod, MaxReceiveCount, DeadLetterMessageRetentionPeriod,
  PnAddressManagerCallbackQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-address_manager_callback'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 300
        MaxReceiveCount: 10
        DelaySeconds: 1

  BatchRequestTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-PNRequest'
      AttributeDefinitions:
        - AttributeName: "correlationId"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "lastReserved"
          AttributeType: "S"
        - AttributeName: "sendStatus"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "correlationId"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "batchId-lastReserved-index"
          KeySchema:
            - AttributeName: batchId
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: "sendStatus-lastReserved-index"
          KeySchema:
            - AttributeName: sendStatus
              KeyType: HASH
            - AttributeName: lastReserved
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PostelBatchTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-NormalizzatoreBatch'
      AttributeDefinitions:
        - AttributeName: "batchId"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "workingTtl"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "batchId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "status-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: "status-workingTtl-index"
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: workingTtl
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CountryTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-Country'
      AttributeDefinitions:
        - AttributeName: "country"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "country"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CapTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-Cap'
      AttributeDefinitions:
        - AttributeName: "cap"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cap"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ApiKeyTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-AnagraficaClient'
      AttributeDefinitions:
        - AttributeName: "cxId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cxId"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Shared lock handling table
  ShedLockTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-addressManager-ShedLock'
      AttributeDefinitions:
        - AttributeName: "_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  AddressManagerTracingLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-address-manager-tracingLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  ApiKeyTableArn:
    Value: !Sub '${ApiKeyTable.Arn}'
  CapTableArn:
    Value: !Sub '${CapTable.Arn}'
  CountryTableArn:
    Value: !Sub '${CountryTable.Arn}'
  PostelBatchTableArn:
    Value: !Sub '${PostelBatchTable.Arn}'
  BatchRequestTableArn:
    Value: !Sub '${BatchRequestTable.Arn}'
  ApiKeyTableName:
    Value: !Ref ApiKeyTable
  CapTableName:
    Value: !Ref CapTable
  CountryTableName:
    Value: !Ref CountryTable
  PostelBatchTableName:
    Value: !Ref PostelBatchTable
  BatchRequestTableName:
    Value: !Ref BatchRequestTable
  EcsLogGroup:
    Value: !GetAtt PnAddressManagerLogGroup.Outputs.LogGroupName
  AddressManagerEventBusArn:
    Value: !GetAtt AddressManagerEventBus.Arn
  AddressManagerEventBusName:
    Value: !GetAtt AddressManagerEventBus.Name
  AddressManagerEventBusDLQArn:
    Value: !GetAtt AddressManagerEventBusDLQ.Arn
  AddressManagerEventBusDLQName:
    Value: !GetAtt AddressManagerEventBusDLQ.QueueName
  AddressManagerEventBusDLQUrl:
    Value: !GetAtt AddressManagerEventBusDLQ.QueueUrl

  # PnAddressManagerInputs Queue
  PnAddressManagerInputsQueueName:
    Value: !GetAtt PnAddressManagerInputsQueue.Outputs.QueueName
  PnAddressManagerInputsQueueARN:
    Value: !GetAtt PnAddressManagerInputsQueue.Outputs.QueueARN
  PnAddressManagerInputsDLQName:
    Value: !GetAtt PnAddressManagerInputsQueue.Outputs.DeadLetterQueueName
  PnAddressManagerInputsDLQURL:
    Value: !GetAtt PnAddressManagerInputsQueue.Outputs.DeadLetterQueueURL
  PnAddressManagerInputsDLQARN:
    Value: !GetAtt PnAddressManagerInputsQueue.Outputs.DeadLetterQueueARN

  # PnAddressManagerCallback Queue
  PnAddressManagerCallbackQueueName:
    Value: !GetAtt PnAddressManagerCallbackQueue.Outputs.QueueName
  PnAddressManagerCallbackQueueARN:
    Value: !GetAtt PnAddressManagerCallbackQueue.Outputs.QueueARN
  PnAddressManagerCallbackDLQName:
    Value: !GetAtt PnAddressManagerCallbackQueue.Outputs.DeadLetterQueueName
  PnAddressManagerCallbackDLQURL:
    Value: !GetAtt PnAddressManagerCallbackQueue.Outputs.DeadLetterQueueURL
  PnAddressManagerCallbackDLQARN:
    Value: !GetAtt PnAddressManagerCallbackQueue.Outputs.DeadLetterQueueARN


  ShedLockTableName:
    Value: !Ref ShedLockTable
  ShedLockTableArn:
    Value: !Sub '${ShedLockTable.Arn}'

 #Lambda Outputs
  AddressManagerTracingLambdaName:
    Value: !Sub "${ProjectName}-address-manager-tracingLambda"