logging.config=config/logback-local.xml

# Runtime mode
pn.env.runtime=DEVELOPMENT

server.port=8093

# Queue inbound event configuration
spring.cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
spring.cloud.aws.sqs.endpoint=${aws.endpoint-url}